### PR TITLE
Use sphere to sign transactions

### PR DESCRIPTION
**Pull request by BasixKOR**
Avoids GraphQL call by locally signing.

### CODE REVIEW

**Comment by kimwz** [comment]
👍 Thank you

**Comment by kimwz** [comment]
I found it late but it seems that await is needed because signTransaction returns a Promise .

**Comment by kimwz** [comment]
After fixing this it still doesn't seem to work.

**Comment by BasixKOR** [comment]
I'll make a fix PR soon, Thanks for the report.

**Pull request merged**
